import { fmtShort, type Trip } from '../lib/trip';
const REGIONS = [
  { title:'Utah · Dinosaur, Arches & Canyonlands',acts:['U'],check:'Check US-40, US-191 between Duchesne and Price, US-6 over Soldier Summit and park access roads. Mountain transfers may have worse conditions than Moab. Stay on paved roads; no Shafer Trail or White Rim in the rental.',fallback:'Quarry Exhibit Hall is indoors. Swap the two Moab park days, shorten exposed walks in rain, and return to Salt Lake early if conditions worsen. Never enter flooded washes or closed roads.',links:[['Utah 511','https://www.udottraffic.utah.gov/'],['Dinosaur conditions','https://www.nps.gov/dino/planyourvisit/conditions.htm'],['Arches conditions','https://www.nps.gov/arch/planyourvisit/conditions.htm'],['Canyonlands conditions','https://www.nps.gov/cany/planyourvisit/conditions.htm']] },
  { title:'Transfer south · Montana & Idaho',acts:['U'],ids:['utSouth','utMoab'],check:'Check US-191, US-20 and I-15, especially mountain passes. October 7 ends in Flat Rock after Bozeman shopping; October 8 ends in Price / Green River; continue to Moab on October 9. Allow charging and museum stops in addition to driving time.',fallback:'Keep Flat Rock as the October 7 overnight. On October 8, keep both museums, shorten the Idaho Falls walk and stop in Price if Green River would be too late.',links:[['Montana 511','https://www.511mt.net/'],['Idaho 511','https://511.idaho.gov/']] },
  { title: 'Washington · Rainier & Hood Canal', acts: ['I'], check: 'Check the Longmire–Paradise road and entrance alerts on the morning you travel. A clear forecast does not guarantee the road is open.', fallback: 'Use the Seattle weather choices: city / Portland time if Rainier is closed or visibility is poor.', links: [['Rainier road status','https://www.nps.gov/mora/planyourvisit/road-status.htm'],['Washington traffic & cameras','https://wsdot.com/Travel/Real-time/Map/']] },
  { title: 'Utah · Bonneville & Logan Canyon', acts: ['II'], ids: ['s1','s2','antelope'], check: 'Check I-80, US-89 and BLM notices before leaving. Keep the rental on permitted roads; wet salt and standing water rule out driving onto the flats.', fallback: 'View Bonneville from the access area or spend the day in Salt Lake. Check the rental terms before any salt-flat driving.', links: [['Utah 511','https://www.udottraffic.utah.gov/'],['Bonneville access','https://www.blm.gov/visit/bonneville-salt-flats']] },
  { title: 'Grand Teton & Yellowstone', acts: ['II','III'], check: 'Check park alerts, road closures and construction, then the forecast at elevation. Early snow can close a pass before its scheduled seasonal closure.', fallback: 'Use an open lower route or a town day. Check the whole route to the next confirmed Tesla charger before entering the park.', links: [['Yellowstone roads','https://www.nps.gov/yell/planyourvisit/parkroads.htm'],['Grand Teton conditions','https://www.nps.gov/grte/planyourvisit/conditions.htm'],['Wyoming 511','https://www.wyoroad.info/']] },
  { title: 'Beartooth, Laurel & Bozeman', acts: ['III','IV'], check: 'Check both Montana and Wyoming road reports. Early snow or poor visibility can close the pass before the seasonal closing date. Check the live status for your travel day.', fallback: 'Select the extra Bozeman day to skip Beartooth. If already in Red Lodge, check the lower route through Laurel and I-90. Do not follow a closed pass just because navigation suggests it.', links: [['Montana 511','https://www.511mt.net/'],['Wyoming 511','https://www.wyoroad.info/'],['Park road calendar','https://www.nps.gov/yell/planyourvisit/parkroads.htm']] },
  { title: 'Idaho · Gallatin to Salt Lake', acts: ['IV'], check: 'Check US-191, US-20 and I-15 for snow, frost, visibility and roadworks. Check conditions for the Craters detour separately if you enable it.', fallback: 'Stay on open main roads, shorten sightseeing and reach the overnight base before conditions deteriorate.', links: [['Idaho 511','https://511.idaho.gov/'],['Montana 511','https://www.511mt.net/'],['Utah 511','https://www.udottraffic.utah.gov/']] },
  { title: 'California · Silicon Valley & the coast', acts: ['V'], check: 'Check Highway 17 and Highway 1 before Santa Cruz, Monterey and the early Half Moon Bay drive. Allow extra time for traffic when returning north; this route does not require the Big Sur section of Highway 1.', fallback: 'Use an open inland route back toward SFO. Be back near San Francisco the night before the flight. If oysters are selected, check Point Reyes alerts instead.', links: [['Caltrans QuickMap','https://quickmap.dot.ca.gov/'],['Point Reyes conditions','https://www.nps.gov/pore/planyourvisit/conditions.htm']] }
];
export function RiskSection({trip}: {trip: Trip}) {
  const ahead = trip.days.filter(d => !d.completed);
  const nextDrive = ahead.find(d => (d.meters ?? 0) > 0);
  return <section id="risks"><div className="shead"><h2>Before today’s drive</h2></div>
    <p className="sub">Open the official road report before setting off, then check mountain weather and the next fuel or charging stop. These links show current conditions; this page does not claim a road is open.</p>
    {nextDrive && <div className="card panel"><h3>Next drive · {fmtShort(nextDrive.date!)} · {nextDrive.title}</h3><p>{nextDrive.leg}</p>{nextDrive.alert && <p>{nextDrive.alert}</p>}<a className="action" href={`#itinerary/${nextDrive.id}`}>Open the day ↗</a></div>}
    <div className="road-grid">{REGIONS.filter(r => ahead.some(d => r.acts.includes(d.act) && (!r.ids || r.ids.includes(d.id)))).map(r => <article className="card panel" key={r.title}><h3>{r.title}</h3><p>{r.check}</p><p><b>If conditions are poor:</b> {r.fallback}</p><div className="road-links">{r.links.map(([label,url]) => <a key={url} className="action" href={url} target="_blank" rel="noreferrer">{label} ↗</a>)}</div></article>)}</div>
    <p className="hint">Only regions still ahead are shown. Open the live reports before driving and follow signs and closure gates over the saved itinerary.</p>
  </section>;
}
