import type { Trip } from '../lib/trip';
const REGIONS = [
  { title: 'Washington · Rainier & Hood Canal', acts: ['I'], check: 'Check the Longmire–Paradise road and entrance alerts on the morning you travel. A clear forecast does not guarantee the road is open.', fallback: 'Use the Seattle weather choices: city / Portland time if Rainier is closed or visibility is poor.', links: [['Rainier road status','https://www.nps.gov/mora/planyourvisit/road-status.htm'],['Washington traffic & cameras','https://wsdot.com/Travel/Real-time/Map/']] },
  { title: 'Utah · Bonneville & Logan Canyon', acts: ['II'], check: 'Check I-80, US-89 and BLM notices before leaving. Keep the rental on permitted roads; wet salt and standing water rule out driving onto the flats.', fallback: 'View Bonneville from the access area or spend the day in Salt Lake. Check the rental terms before any salt-flat driving.', links: [['Utah 511','https://www.udottraffic.utah.gov/'],['Bonneville access','https://www.blm.gov/visit/bonneville-salt-flats']] },
  { title: 'Grand Teton & Yellowstone', acts: ['II','III'], check: 'Check park alerts, road closures and construction, then the forecast at elevation. Early snow can close a pass before its scheduled seasonal closure.', fallback: 'Use an open lower route or a town day. Check the whole route to the next confirmed Tesla charger before entering the park.', links: [['Yellowstone roads','https://www.nps.gov/yell/planyourvisit/parkroads.htm'],['Grand Teton conditions','https://www.nps.gov/grte/planyourvisit/conditions.htm'],['Wyoming 511','https://www.wyoroad.info/']] },
  { title: 'Beartooth, Laurel & Bozeman', acts: ['III','IV'], check: 'Check both Montana and Wyoming road reports. The 2026 planned Beartooth closing date is October 12, weather permitting; that is not a promise that your travel day will be open.', fallback: 'Select the extra Bozeman day to skip Beartooth. If already in Red Lodge, check the lower route through Laurel and I-90. Do not follow a closed pass just because navigation suggests it.', links: [['Montana 511','https://www.511mt.net/'],['Wyoming 511','https://www.wyoroad.info/'],['Park road calendar','https://www.nps.gov/yell/planyourvisit/parkroads.htm']] },
  { title: 'Idaho · Gallatin to Salt Lake', acts: ['IV'], check: 'Check US-191, US-20 and I-15 for snow, frost, visibility and roadworks. Check conditions for the Craters detour separately if you enable it.', fallback: 'Stay on open main roads, shorten sightseeing and reach the overnight base before conditions deteriorate.', links: [['Idaho 511','https://511.idaho.gov/'],['Montana 511','https://www.511mt.net/'],['Utah 511','https://www.udottraffic.utah.gov/']] },
  { title: 'California · Silicon Valley & the coast', acts: ['V'], check: 'Check Highway 17 and Highway 1 before Santa Cruz, Monterey and the early Half Moon Bay drive. Allow extra time for traffic when returning north; this route does not require the Big Sur section of Highway 1.', fallback: 'Use an open inland route back toward SFO. Be back near San Francisco the night before the flight. If oysters are selected, check Point Reyes alerts instead.', links: [['Caltrans QuickMap','https://quickmap.dot.ca.gov/'],['Point Reyes conditions','https://www.nps.gov/pore/planyourvisit/conditions.htm']] }
];
export function RiskSection({trip}: {trip: Trip}) {
  return <section id="risks"><div className="shead"><h2>Before today’s drive</h2></div>
    <p className="sub">Open the official road report before setting off, then check mountain weather and the next fuel or charging stop. These links show current conditions; this page does not claim a road is open.</p>
    <div className="road-grid">{REGIONS.filter(r => trip.days.some(d => r.acts.includes(d.act))).map(r => <article className="card panel" key={r.title}><h3>{r.title}</h3><p>{r.check}</p><p><b>If conditions are poor:</b> {r.fallback}</p><div className="road-links">{r.links.map(([label,url]) => <a key={url} className="action" href={url} target="_blank" rel="noreferrer">{label} ↗</a>)}</div></article>)}</div>
    <p className="hint">Seasonal information reviewed September 13, 2026. Follow signs and closure gates over the saved map or itinerary.</p>
  </section>;
}
