import assert from 'node:assert/strict';
import { CHECKS, CHECK_CATEGORIES, checksForTrip, normalizeChecks } from '../src/data/checklist';
import { buildTrip } from '../src/lib/trip';
import { DEFAULT_SEATTLE } from '../src/data/seattle';
const base = buildTrip(new Set());
assert.equal(new Set(CHECKS.map(c=>c.id)).size,CHECKS.length);
assert.ok(CHECKS.every(c=>CHECK_CATEGORIES.some(g=>g.id===c.category)));
assert.deepEqual(normalizeChecks(['driver','driver','bad','turo']),['driver','turo']);
const cars = checksForTrip(base).filter(c=>c.when);
assert.equal(cars.length,3);
assert.ok(cars[0].when!.includes('Sep 24 – Sep 28'));
assert.ok(cars[1].when!.includes('Sep 29 – Oct 9'));
assert.ok(cars[2].when!.includes('Oct 11 – Oct 12'));
const early = checksForTrip(buildTrip(new Set(),'balanced',{}, {...DEFAULT_SEATTLE,weather:'rain',flight:'mon-am'}));
assert.ok(early.find(c=>c.id==='sea-car-20260924')?.when?.includes('Sep 27'));
console.log('✓ Checklist categories, unique stable IDs, preserved completion and rental dates that follow weather variants');

const { normalizeJournal } = await import('../src/lib/journal');
const { recordedFood, remainingDays } = await import('../src/lib/tripKit');
const variants=['arrival','hood','rainier','seattle','redmond','salt','antelopeMontpelier'];
const journal=normalizeJournal(Object.fromEntries(variants.map((variant,i)=>[`2026-09-${24+i}`,{variant,title:'Recorded day',note:'Ate at Shake Shack.\nRain after oysters.',status:'done'}])));
const started=buildTrip(new Set(),'motel',{},DEFAULT_SEATTLE,{},journal);
const startedChecks=checksForTrip(started);
for(const id of ['sea-car-20260924','dates-20260929','flight-sea-slc','arrival-inn','oyster-bay-20260925','hama-20260925','topaz-calendar','sunrise','tomales-20260924','turo']) assert.ok(startedChecks.find(c=>c.id===id)?.retired,id);
for(const id of ['california-car','flight-slc-sfo','slc-return-review','mountain-stays','node-palo-alto','red-butte','pumpkin-weighoff','bear']) assert.ok(!startedChecks.find(c=>c.id===id)?.retired,id);
assert.equal(startedChecks.length,CHECKS.length,'Archiving must retain IDs and saved completion history');
assert.deepEqual(normalizeChecks(['sea-car-20260924','arrival-inn']),['sea-car-20260924','arrival-inn']);
assert.equal(remainingDays(started)[0].id,'s3');
assert.deepEqual(recordedFood(started.days[0]),['Ate at Shake Shack.']);
assert.deepEqual(recordedFood(started.days[7]),[]);
const oysterChecks=checksForTrip(buildTrip(new Set(['oysters']),'motel',{},DEFAULT_SEATTLE,{},journal));
assert.ok(!oysterChecks.find(c=>c.id==='tomales-20260924')?.retired);
assert.ok(oysterChecks.find(c=>c.id==='pumpkin-weighoff')?.retired);
console.log('✓ In-progress checklist preserves IDs, retires past tasks, follows coast modules and separates recorded meals from future days');
