import assert from 'node:assert/strict';
import { buildTrip, ROUTES } from '../src/lib/trip';
import { DEFAULT_SEATTLE } from '../src/data/seattle';
import { normalizeJournal } from '../src/lib/journal';
import { validField } from '../shared/trip-schema.mjs';
const record = {variant:'seattle', title:'A completed city visit',note:'Confirmed places only',status:'done'};
assert.equal(validField('journal:2026-02-30',record),false);
assert.equal(validField('journal:2026-09-30',{...record,unexpected:'secret'}),false);
const journal = normalizeJournal({'2026-09-30':record,'2026-10-01':{...record,variant:'montpelierTetons',title:'Next leg',note:'',status:'planned'}});
const trip=buildTrip(new Set(['antelope','olympic']),'motel',{},DEFAULT_SEATTLE,{s2:{type:'bed',place:'Chosen hotel',note:'Private note'}},journal);
assert.equal(trip.days.length,20);
assert.equal(trip.days[6].id,'s2');
assert.equal(trip.days[6].completed,true);
assert.equal(trip.days[6].sleep?.where,'Chosen hotel');
assert.equal(trip.days[6].sleep?.note,'Private note');
assert.equal(trip.days[6].meters,0);
assert.equal(trip.days[6].routeId,'recorded');
assert.deepEqual(trip.days[6].hi,['Confirmed places only']);
assert.equal(trip.days[7].id,'s3');
assert.equal(trip.days[7].routeId,'montpelierTetons');
assert.equal(trip.days[7].completed,false);
assert.match(trip.days[7].alert!,/September 30/);
assert.ok(ROUTES.montpelierTetons.line[0][0]>42.3);
assert.equal(new Date(trip.days.at(-1)!.date!).toISOString().slice(0,10),'2026-10-13');
assert.equal(buildTrip(new Set()).days[6].completed,undefined);
console.log('✓ Private dated records, validation, past-module protection, preserved stays, connected onward route and fixed return');
