import assert from 'node:assert/strict';
import { buildTrip } from '../src/lib/trip';
import { DEFAULT_SEATTLE } from '../src/data/seattle';
const base = buildTrip(new Set());
assert.match(base.days.find(d=>d.id==='sf3')!.sleep!.where,/Santa Cruz/);
assert.match(base.days.find(d=>d.id==='sf2')!.title,/Monterey/);
const oysters=buildTrip(new Set(['oysters']));
assert.match(oysters.days.find(d=>d.id==='sf3')!.sleep!.where,/San Francisco/);
assert.match(oysters.days.find(d=>d.id==='sf2')!.title,/oysters/);
const wolves=buildTrip(new Set(['wolves']));
assert.ok(wolves.days.some(d=>d.id==='s5b'));
assert.ok(!wolves.days.some(d=>d.id==='sf2'));
assert.match(wolves.days.find(d=>d.id==='sf3')!.sleep!.where,/San Francisco/);
assert.equal(wolves.days.length,20);
const stay={place:'Our chosen inn',note:'Check in after 4pm',type:'bed' as const};
const chosen=buildTrip(new Set(),'balanced',{},DEFAULT_SEATTLE,{sf3:stay});
assert.equal(chosen.days.find(d=>d.id==='sf3')!.sleep!.where,stay.place);
assert.equal(chosen.days.find(d=>d.id==='sf3')!.sleep!.note,stay.note);
assert.match(chosen.days.find(d=>d.id==='sf3')!.sleep!.suggestedWhere!,/Santa Cruz/);
const car={place:'Chosen campsite',note:'',type:'car' as const};
const consecutive=buildTrip(new Set(),'balanced',{},DEFAULT_SEATTLE,{s4:car,s4b:car,s5:car});
assert.ok(consecutive.days.find(d=>d.id==='s5')!.sleep!.streak!>=3,'Chosen car nights remain explicit, with a streak warning');
console.log('✓ Coast / oyster alternatives, wolf-day tradeoff, flight window, saved stays and consecutive car choices');
